[[plugins]]
repo = 'Shougo/dein.vim'

# 表示
[[plugins]]
repo = 'Shougo/vimfiler'

[[plugins]]
repo = 'vim-airline/vim-airline'

[[plugins]]
repo = 'bronson/vim-trailing-whitespace'

[[plugins]]
repo = 'Yggdroot/indentLine'

# 補完
[[plugins]]
repo = 'Shougo/neocomplete.vim'

[[plugins]]
repo = 'osyo-manga/vim-monster'

[[plugins]]
repo = 'alpaca-tc/vim-endwise.git'

[[plugins]]
repo = 'Townk/vim-autoclose'

[[plugins]]
repo = 'Shougo/neosnippet.vim'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'alvan/vim-closetag'

# 検索
[[plugins]]
repo = 'ctrlpvim/ctrlp.vim'

[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'soramugi/auto-ctags.vim'

[[plugins]]
repo = 'rking/ag.vim'

# tool
[[plugins]]
repo = 'tell-k/vim-browsereload-mac'

[[plugins]]
repo = 'szw/vim-tags'

[[plugins]]
repo = 'iberianpig/tig-explorer.vim'

# syntax
[[plugins]]
repo = 'vim-syntastic/syntastic'

[[plugins]]
repo = 'cespare/vim-toml'

[[plugins]]
repo = 'kchmck/vim-coffee-script'

[[plugins]]
repo = 'thoughtbot/vim-rspec'

[[plugins]]
repo = 'slim-template/vim-slim'

[[plugins]]
repo = 'othree/html5.vim'

[[plugins]]
repo = 'gisphm/vim-gitignore'

[[plugins]]
repo = 'chase/vim-ansible-yaml'

[[plugins]]
repo = 'pangloss/vim-javascript'

[[plugins]]
repo = 'mxw/vim-jsx'

[[plugins]]
repo = 'posva/vim-vue'

[[plugins]]
repo = 'mxw/vim-jsx'

[[plugins]]
repo = 'editorconfig/editorconfig-vim'

[[plugins]]
repo = 'vim-ruby/vim-ruby'

[[plugins]]
repo = 'wavded/vim-stylus'

[[plugins]]
repo = 'chr4/nginx.vim'

# 静的解析
[[plugins]]
repo = 'scrooloose/syntastic'

[[plugins]]
repo = 'ngmy/vim-rubocop'

[[plugins]]
repo = 'sekel/vim-vue-syntastic'

# Formatter
[[plugins]]
repo = 'ruby-formatter/rufo-vim'

# Utilities
[[plugins]]
repo = 'tpope/vim-pathogen'
